### ISSUE TITLE
branch_id in duikersifonhevel

### ISSUE THREAD

**Issue by BramWijnants** [HetWaterschapshuis/HyDAMOValidatieModule#14]
Im getting errors on 2 validation rules in duikersifonhevel because of a missing keyword 'branch_id'. This branch_id is asked in the compare_longitudinal functions. Those are getting called by the validation rule with id 10 en 11. 

Error traces to line 299 of topologic.py:

branch_id = row["branch_id"]

The dataset I use doesnt have a "branch_id", it does have a "code" or "globalid". Is this just a mapping problem and am I suppose to rename branch_id to a id field within the layer?

Output in result.json:
"errors": [
    "validation_rule niet uitgevoerd. Inspecteer de invoer voor deze regel: (object 'duikersifonhevel', rule_id '10', function: 'compare_longitudinal', input_variables: {'parameter': 'hoogtebinnenonderkantbov', 'compare_object': 'profiellijn', 'compare_parameter': 'bodemhoogte_marge_min', 'logical_operator': 'GT', 'direction': 'upstream'}, Reason (Exception): 'branch_id')",
    "validation_rule niet uitgevoerd. Inspecteer de invoer voor deze regel: (object 'duikersifonhevel', rule_id '11', function: 'compare_longitudinal', input_variables: {'parameter': 'hoogtebinnenonderkantbene', 'compare_object': 'profiellijn', 'compare_parameter': 'bodemhoogte_marge_min', 'logical_operator': 'GT', 'direction': 'downstream'}, Reason (Exception): 'branch_id')",
],

Full traceback:

duikersifonhevel validation_rule 10 crashed
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3799             try:
-> 3800                 return self._engine.get_loc(casted_key)
   3801             except KeyError as err:

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'branch_id'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-4-ac3a6f31e1eb> in <module>
      4                              log_level="INFO",
      5                             schemas_path=schemas_path)
----> 6 datamodel, layer_summary, result_summary = hydamo_validator(directory=directory, raise_error=True)
      7 result_summary.to_dict()

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\hydamo_validation\validator.py in _validator(directory, output_types, log_level, coverages, schemas_path, raise_error)
    270             result_summary.to_json(results_path)
    271         if raise_error:
--> 272             raise e
    273         else:
    274             result_summary.to_dict()

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\hydamo_validation\validator.py in _validator(directory, output_types, log_level, coverages, schemas_path, raise_error)
    231         # do logical validation: append result to layers_summary
    232         result_summary.status = "logical validation"
--> 233         layers_summary, result_summary = logical_validation.execute(
    234             datamodel,
    235             validation_rules_sets,

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\hydamo_validation\logical_validation.py in execute(datamodel, validation_rules_sets, layers_summary, result_summary, log_level, raise_error)
    319                 )
    320                 if raise_error:
--> 321                     raise e
    322                 else:
    323                     pass

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\hydamo_validation\logical_validation.py in execute(datamodel, validation_rules_sets, layers_summary, result_summary, log_level, raise_error)
    265                     hasattr(datamodel, "hydroobject")
    266                 ):
--> 267                     result_series = _process_topologic_function(
    268                         getattr(datamodel, object_layer),
    269                         datamodel,

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\hydamo_validation\logical_validation.py in _process_topologic_function(gdf, datamodel, function, input_variables)
     34 
     35 def _process_topologic_function(gdf, datamodel, function, input_variables):
---> 36     return getattr(topologic_functions, function)(gdf, datamodel, **input_variables)
     37 
     38 

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\hydamo_validation\functions\topologic.py in compare_longitudinal(gdf, datamodel, parameter, compare_object, compare_parameter, direction, logical_operator)
    610     """
    611     compare_gdf = getattr(datamodel, compare_object)
--> 612     return gdf.apply(
    613         lambda x: _compare_longitudinal(x,
    614                                         parameter,

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\geopandas\geodataframe.py in apply(self, func, axis, raw, result_type, args, **kwargs)
   1388     @doc(pd.DataFrame)
   1389     def apply(self, func, axis=0, raw=False, result_type=None, args=(), **kwargs):
-> 1390         result = super().apply(
   1391             func, axis=axis, raw=raw, result_type=result_type, args=args, **kwargs
   1392         )

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\pandas\core\frame.py in apply(self, func, axis, raw, result_type, args, **kwargs)
   9556             kwargs=kwargs,
   9557         )
-> 9558         return op.apply().__finalize__(self, method="apply")
   9559 
   9560     def applymap(

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\pandas\core\apply.py in apply(self)
    739             return self.apply_raw()
    740 
--> 741         return self.apply_standard()
    742 
    743     def agg(self):

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\pandas\core\apply.py in apply_standard(self)
    866 
    867     def apply_standard(self):
--> 868         results, res_index = self.apply_series_generator()
    869 
    870         # wrap results

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\pandas\core\apply.py in apply_series_generator(self)
    882             for i, v in enumerate(series_gen):
    883                 # ignore SettingWithCopy here in case the user mutates
--> 884                 results[i] = self.f(v)
    885                 if isinstance(results[i], ABCSeries):
    886                     # If we have a view on v, we need to make a copy because

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\hydamo_validation\functions\topologic.py in <lambda>(x)
    611     compare_gdf = getattr(datamodel, compare_object)
    612     return gdf.apply(
--> 613         lambda x: _compare_longitudinal(x,
    614                                         parameter,
    615                                         compare_gdf,

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\hydamo_validation\functions\topologic.py in _compare_longitudinal(row, parameter, compare_gdf, compare_parameter, direction, logical_operator)
    272                           logical_operator):
    273     branch_id = row["branch_id"]
--> 274     select_gdf = compare_gdf.loc[compare_gdf["branch_id"] == branch_id]
    275     right = None
    276     result = None

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\geopandas\geodataframe.py in __getitem__(self, key)
  1325         GeoDataFrame.
   1326         """
-> 1327         result = super().__getitem__(key)
   1328         geo_col = self._geometry_column_name
   1329         if isinstance(result, Series) and isinstance(result.dtype, GeometryDtype):

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3803             if self.columns.nlevels > 1:
   3804                 return self._getitem_multilevel(key)
-> 3805             indexer = self.columns.get_loc(key)
   3806             if is_integer(indexer):
   3807                 indexer = [indexer]

P:\WinPython\WPy64-3920Watersysteemtoets\python-3.9.2.amd64\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3800                 return self._engine.get_loc(casted_key)
   3801             except KeyError as err:
-> 3802                 raise KeyError(key) from err
   3803             except TypeError:
   3804                 # If we have a listlike key, _check_indexing_error will raise

KeyError: 'branch_id'

**Comment by d2hydro** [comment]
Hi Bram,

I registered your issue at HYV-200 in our system. It is preferred to use the e-mail in https://hkvconfluence.atlassian.net/wiki/spaces/VAL/pages/1991278596/Gebruikersregistratie as it will be picked up by our support automatically next time.

In response to your issue:
`branch_id` is an "internal column" that is generated by calling the `snap_to_branch` method in the ExtendedGeoDataFrame: https://github.com/HetWaterschapshuis/HyDAMOValidatieModule/blob/a1b09803d3f9e3e60784b67eded6fe016491c72b/hydamo_validation/datamodel.py#L243. Seems that method is not called.

It seems you are running the code in a python environment. Could you provide a small dataset and code-lines by which I can reproduce the error above?

Thanks!

Daniel

**Comment by d2hydro** [comment]
Hi @BramWijnants,

Thanks for sharing your dataset, its been downloaded. I'll reproduce and hopefully solve this issue in the coming sprint resulting in a new release. Should take no longer than 2 weeks. I'll keep you posted in this thread.

Cheers

**Comment by d2hydro** [comment]
Issue is reproduced; `compare_longitudinal` needs both layers, in this case `duikersifonhevel` and `profiellijn` to be snapped to the network (branches). 

I think snapping needs some "refinement" in general in a new issue, but from 1.3 we'll force snapping

```
# snap layers to to branches
compare_gdf.snap_to_branch(datamodel.hydroobject, snap_method="overall")
gdf.snap_to_branch(datamodel.hydroobject, snap_method="overall")
```
